-- ----------------------------------------------------------------------------
-- 0200 — recreate mfg_sales_orders_with_payment_totals to include the new SO
-- columns (PROD HOTFIX). The SO LIST reads this view (for balance_centi_live);
-- the view enumerates columns explicitly, so the HC fields added to mfg_sales_orders
-- by 0197 (possession_date/house_type/replacement_disposal/referral) + the amend
-- dates by 0199 (amend_date_from_customer/amended_delivery_date) were NOT in the
-- view → the list query (which selects them via the shared HEADER) 500'd
-- ("Failed to load"). CREATE OR REPLACE keeps grants; new columns appended at the
-- end (required by CREATE OR REPLACE VIEW). Apply 0199 BEFORE this (amend cols
-- must exist). Re-run safe.
-- ----------------------------------------------------------------------------

CREATE OR REPLACE VIEW mfg_sales_orders_with_payment_totals AS
SELECT so.doc_no,
  so.transfer_to,
  so.so_date,
  so.branding,
  so.debtor_code,
  so.debtor_name,
  so.agent,
  so.sales_location,
  so.ref,
  so.po_doc_no,
  so.venue,
  so.address1,
  so.address2,
  so.address3,
  so.address4,
  so.phone,
  so.mattress_sofa_centi,
  so.bedframe_centi,
  so.accessories_centi,
  so.others_centi,
  so.local_total_centi,
  so.balance_centi,
  so.total_cost_centi,
  so.total_revenue_centi,
  so.total_margin_centi,
  so.margin_pct_basis,
  so.line_count,
  so.currency,
  so.status,
  so.remark2,
  so.remark3,
  so.remark4,
  so.note,
  so.processing_date,
  so.sales_exemption_expiry,
  so.created_at,
  so.created_by,
  so.updated_at,
  so.customer_id,
  so.customer_po,
  so.customer_po_id,
  so.customer_po_date,
  so.customer_po_image_b64,
  so.hub_id,
  so.hub_name,
  so.customer_state,
  so.customer_delivery_date,
  so.internal_expected_dd,
  so.linked_do_doc_no,
  so.ship_to_address,
  so.bill_to_address,
  so.install_to_address,
  so.subtotal_sen,
  so.overdue,
  so.email,
  so.customer_type,
  so.salesperson_id,
  so.city,
  so.postcode,
  so.building_type,
  so.emergency_contact_name,
  so.emergency_contact_phone,
  so.emergency_contact_relationship,
  so.target_date,
  so.customer_so_no,
  so.payment_method,
  so.installment_months,
  so.merchant_provider,
  so.deposit_centi,
  so.paid_centi,
  so.approval_code,
  so.payment_date,
  so.mattress_sofa_cost_centi,
  so.bedframe_cost_centi,
  so.accessories_cost_centi,
  so.others_cost_centi,
  so.customer_country,
  so.venue_id,
  so.priority_rank,
  so.priority_set_at,
  so.priority_set_by,
  so.priority_reason,
  so.allocation_warehouse_id,
  so.proceeded_at,
  so.fabric_tier_addon_centi,
  so.delivery_fee_centi,
  so.cross_category_source_doc_no,
  so.signature_b64,
  so.slip_key,
  so.slip_state,
  so.service_centi,
  so.service_cost_centi,
  COALESCE(p.paid_total, 0::bigint) AS paid_total_centi,
  GREATEST(so.local_total_centi - COALESCE(p.paid_total, 0::bigint), 0::bigint) AS balance_centi_live,
  so.possession_date,
  so.house_type,
  so.replacement_disposal,
  so.referral,
  so.amend_date_from_customer,
  so.amended_delivery_date,
  so.delivery_state
FROM mfg_sales_orders so
LEFT JOIN ( SELECT mfg_sales_order_payments.so_doc_no,
    sum(mfg_sales_order_payments.amount_centi) AS paid_total
   FROM mfg_sales_order_payments
  GROUP BY mfg_sales_order_payments.so_doc_no) p ON p.so_doc_no = so.doc_no;
